on:
  pull_request:
    branches:
      - "*"

jobs:
  changed_files:
    runs-on: ubuntu-latest
    outputs:
      new_study_dir: ${{steps.new-dir.outputs.NEW_DIR_NAME}}
    steps:
      - name: Get New Directories Added
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v37
        with:
          dir_names: "true"
      - name: Extract Directory Name of New Study
        id: new-dir
        run: |
          echo ${ echo "${{ steps.changed-files-dir-names.outputs.added_files }}" | awk '{print $1}' }
          echo "NEW_DIR_NAME=${ echo ${{ steps.changed-files-dir-names.outputs.added_files }} | awk {print $1} }" >> $GITHUB_OUTPUT

  preview:
    needs: changed_files
    runs-on: ubuntu-latest
    container: docker.io/okteto/okteto:2.19.0
    # defaults:
    #   run:
    #     working-directory: 
    steps:
      - name: Checkout Datahub Repository
        uses: actions/checkout@v3

      # - name: Checkout cbioportal-docker-compose Repository
      #   uses: actions/checkout@v3
      #   with:
      #     repository: justinjao/cbioportal-docker-compose
      #     ref: test-master
      #     path: cbioportal-docker-compose


      - name: Context
        uses: okteto/context@latest
        with:
          url: ${{secrets.OKTETO_URL}}
          token: ${{ secrets.OKTETO_TOKEN }}


      - name: Deploy preview environment
        uses: okteto/deploy-preview@latest
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: pr-${{ github.event.number }}-justinjao
          file: preview_infrastructure/cbioportal-docker-compose/okteto.yml
          timeout: 15m
    
      - name: Wait For Response
        uses: nev7n/wait_for_response@v1.0.1
        with:
          url: 'https://cbioportal-pr-${{ github.event.number }}-justinjao.cloud.okteto.net/'
          responseCode: 200
          timeout: 600000 # 10 minutes
          interval: 30000 # 30 seconds

      - name: "Activate Namespace"
        uses: okteto/namespace@latest
        with:
          namespace: pr-${{github.event.number}}-justinjao

      - name: Kubectl test
        run: |
          okteto kubeconfig
          kubectl exec -it deployment/cbioportal -- metaImport.py -u http://localhost:8080 -s ..${{needs.changed_files.outputs.new_study_dir}}/ -o
